// Issue #160: generate instrumented copies of the canonical target case from
// tests/football-context-integration.spec.mjs. The only edits are the fixture
// import, Node brackets around the answer and the unchanged 2500ms assertion,
// and (control.spec.mjs only) the labeled synthetic intervention. A round trip
// that removes exactly those edits must reproduce the canonical file byte for
// byte, or generation throws.
import path from 'node:path';
import { sha256 } from './instrument.mjs';

export const CANONICAL = 'tests/football-context-integration.spec.mjs';
export const TARGET_TITLE = 'committed special results survive defense-transition and halftime overlays, then clear on Continue';
export const FULL_COPY = 'football-context-integration.diag160.spec.mjs';

const IMPORT = "import { test, expect } from './curriculum-fixture.mjs';\n";
const ASSERTION = 'expect(page.locator(scenario.overlay)).toBeVisible({ timeout: 2500 })';
const ANSWER = "    await beginSpecialPlay(page, 'punt', 'offense', null, scenario.period);\n"
  + "    const committed = await resolveSpecialPolicy(page, 'firstTryCorrect');\n";
const CHAIN = '    const diagChain = diag160.chain(page, scenario.overlay);\n';
const ANSWER_START = "    diag160.mark(page, diagChain, 'answerStart');\n";
const ANSWER_END = "    diag160.mark(page, diagChain, 'answerEnd');\n";
const INTERVENE = '    await diag160.intervene(page, diagChain); // SYNTHETIC CONTROL ONLY\n';
const SETTLE = `    await diag160.settle(page, diagChain, () => ${ASSERTION});\n`;

function indexOnce(text, find, label) {
  const n = text.split(find).length - 1;
  if (n !== 1) throw new Error(`diag160 gen: ${label} found ${n} times`);
  return text.indexOf(find);
}
const swap = (text, find, replacement, label) => {
  indexOnce(text, find, label);
  return text.replace(find, () => replacement);
};
const lineOf = (text, index) => text.slice(0, index).split('\n').length;

function editTest(span, control) {
  const answered = swap(span, ANSWER, CHAIN + ANSWER.replace('    const committed', ANSWER_START + '    const committed') + ANSWER_END, 'answer');
  return swap(answered, `    await ${ASSERTION};\n`, (control ? INTERVENE : '') + SETTLE, 'assertion');
}

function unedit(text) {
  let out = text;
  for (const added of [CHAIN, ANSWER_START, ANSWER_END, INTERVENE]) out = out.split(added).join('');
  return out.split(SETTLE).join(`    await ${ASSERTION};\n`);
}

export function generate(source, { genDir, fixturePath }) {
  if (indexOnce(source, IMPORT, 'import') !== 0) throw new Error('diag160 gen: canonical import is not first');
  const helperEnd = indexOnce(source, '\nfunction readPointer(', 'helper end') + 1;
  const testStart = indexOnce(source, `test('${TARGET_TITLE}'`, 'target test');
  const close = source.indexOf('\n});\n', testStart);
  if (close === -1) throw new Error('diag160 gen: target test end not found');
  const testEnd = close + '\n});\n'.length;
  const helpers = source.slice(IMPORT.length, helperEnd);
  const span = source.slice(testStart, testEnd);
  if (span.split(ASSERTION).length !== 2) throw new Error('diag160 gen: target assertion count');

  const rel = path.relative(genDir, fixturePath).split(path.sep).join('/');
  const header = `// GENERATED by scripts/diag-160/gen-spec.mjs from ${CANONICAL} sha256 ${sha256(source)}. Diagnostic only; do not edit.\n`;
  const imports = `import { test, expect, diag160 } from '${rel.startsWith('.') ? rel : `./${rel}`}';\n`;
  const files = {
    'target.spec.mjs': header + imports + helpers + '\n' + editTest(span, false),
    'control.spec.mjs': header + imports + helpers + '\n' + editTest(span, true),
    [FULL_COPY]: header + imports + source.slice(IMPORT.length, testStart) + editTest(span, false) + source.slice(testEnd),
  };

  // Round trips: every assertion and line outside the edits is canonical.
  const restore = text => IMPORT + unedit(text.slice(header.length + imports.length));
  if (restore(files[FULL_COPY]) !== source) throw new Error('diag160 gen: full copy round trip differs');
  for (const name of ['target.spec.mjs', 'control.spec.mjs']) {
    if (restore(files[name]) !== IMPORT + helpers + '\n' + span) throw new Error(`diag160 gen: ${name} round trip differs`);
  }

  return {
    files,
    manifest: {
      canonical: CANONICAL,
      canonicalSha256: sha256(source),
      helperSpan: { lines: [1, lineOf(source, helperEnd) - 1], sha256: sha256(source.slice(0, helperEnd)) },
      testSpan: { lines: [lineOf(source, testStart), lineOf(source, testEnd) - 1], sha256: sha256(span) },
      assertion: ASSERTION,
      roundTrip: 'exact',
      outputs: Object.fromEntries(Object.entries(files).map(([name, text]) => [name, sha256(text)])),
    },
  };
}
